serial:
    port: '/dev/ttyACM0'
    baud: 115200

subplots:
    -
        pos: 111
        title: 'Lidar scan'
        min: 0
        max: 5000
data:
    read:
        -
            label: 'angle'
            type: 'uint16'
            pos: 111
        -
            label: 'distance'
            type: 'uint16'
            pos: 111
