serial:
    port: '/dev/ttyACM0'
    baud: 115200

subplots:
    -
        pos: 111
        title: 'Speed'
        min: -5
        max: 5
data:
    read:
        -
            label: 'Input1'
            type: 'float'
            pos: 111
        -
            label: 'Setpoint1'
            type: 'float'
            pos: 111
        -
            label: 'Input2'
            type: 'float'
            pos: 111
        -
            label: 'Setpoint2'
            type: 'float'
            pos: 111
    write:
        -
            type: 'float'
