# Port name of the serial port
port_name: '/dev/ttyACM0'
# Baud rate of the serial connection
baud_rate: 115200
# Sample time in milliseconds
sample_time: 10
# PID coefficients
kp: 0.02
ki: 0
kd: 0
# Reference
setpoint: 1200
mode: true
anti_windup: true
