# Port name of the serial port
port_name: '/dev/ttyACM0'
# Baud rate of the serial connection
baud_rate: 115200
# Sample time in milliseconds
sample_time: 10
# PID coefficients
kp: 2
ki: 0.3
kd: 5
# Reference
reference: 1200
mode: true
anti_windup: true
