# Port name of the serial port
port_name: '/dev/ttyACM0'
# Baud rate of the serial connection
baud_rate: 115200
# Sample time in milliseconds
sample_time: 1
# PID coefficients
kp: 1
ki: 0
kd: 12
# Reference
max_setpoint: 1200
mode: true
anti_windup: true
